services:
  db:
    image: postgres:14-alpine
    restart: always
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mastodon"]
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mastodon
      POSTGRES_DB: mastodon
      POSTGRES_PASSWORD: mastodon
    logging:
      driver: fluentd
      options:
        tag: docker.mstdn_aoirint_com.db.{{.ID}}
        fluentd-async: "true"

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./volumes/redis:/data
    logging:
      driver: fluentd
      options:
        tag: docker.mstdn_aoirint_com.redis.{{.ID}}
        fluentd-async: "true"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Des.enforce.bootstrap.checks=true"
      - "xpack.license.self_generated.type=basic"
      - "xpack.security.enabled=false"
      - "xpack.watcher.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "bootstrap.memory_lock=true"
      - "cluster.name=es-mastodon"
      - "discovery.type=single-node"
      - "thread_pool.write.queue_size=1000"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: fluentd
      options:
        tag: docker.mstdn_aoirint_com.es.{{.ID}}
        fluentd-async: "true"

  web:
    image: ghcr.io/mastodon/mastodon:v4.2.12
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    depends_on:
      - db
      - redis
      - es
    extra_hosts:
      - "minio.aoirint.com:${MINIO_AOIRINT_COM_IP_ADDRESS:?}"
    logging:
      driver: fluentd
      options:
        tag: docker.mstdn_aoirint_com.web.{{.ID}}
        fluentd-async: "true"

  streaming:
    image: ghcr.io/mastodon/mastodon:v4.2.12
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    depends_on:
      - db
      - redis
    extra_hosts:
      - "minio.aoirint.com:${MINIO_AOIRINT_COM_IP_ADDRESS:?}"
    logging:
      driver: fluentd
      options:
        tag: docker.mstdn_aoirint_com.streaming.{{.ID}}
        fluentd-async: "true"

  sidekiq:
    image: ghcr.io/mastodon/mastodon:v4.2.12
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    extra_hosts:
      - "minio.aoirint.com:${MINIO_AOIRINT_COM_IP_ADDRESS:?}"
    logging:
      driver: fluentd
      options:
        tag: docker.mstdn_aoirint_com.sidekiq.{{.ID}}
        fluentd-async: "true"

  nginx:
    image: nginx:latest
    restart: always
    networks:
      - external_network
    ports:
      - "${NGINX_HOST_PORT:?}:80"
    volumes:
      - ./nginx_templates:/etc/nginx/templates
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
    logging:
      driver: fluentd
      options:
        tag: docker.mstdn_aoirint_com.nginx.{{.ID}}
        fluentd-async: "true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    networks:
      - external_network
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:-}
    logging:
      driver: fluentd
      options:
        tag: docker.mstdn_aoirint_com.cloudflared.{{.ID}}
        fluentd-async: "true"

networks:
  external_network:
  internal_network:
    internal: true
